/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=cloud/wrangler.jsonc --include-runtime=false --env-interface=CloudflareBindings cloud/worker-configuration.d.ts` (hash: 0425d913ca9813127eb5ac685463b244)
interface __BaseEnv_CloudflareBindings {
	REPORTS: R2Bucket;
	CORPUS: R2Bucket;
	DB: D1Database;
	WEBHOOK_QUEUE: Queue;
	CORPUS_QUEUE: Queue;
	ASSETS: Fetcher;
	APP_URL: "https://app.juror.dev";
	LEGACY_APP_URL: "https://juror-cloud.cderinbogaz-5f3.workers.dev";
	GLAMA_MAINTAINER_EMAIL: "";
	GITHUB_APP_SLUG: "juror-cloud";
	CORPUS_CONSENT_VERSION: "2026-08-21.v1";
	DEV_BYPASS_AUTH: "false";
	STRIPE_METER_EVENT_NAME: "juror_cloud_usage_micro_usd";
	STRIPE_PRICE_ID: "unconfigured";
	CONTAINER_CPU_MICRO_USD_PER_VCPU_SECOND: "20";
	CONTAINER_MEMORY_MICRO_USD_PER_GIB_SECOND: "2.5";
	CONTAINER_DISK_MICRO_USD_PER_GB_SECOND: "0.07";
	R2_STORAGE_MICRO_USD_PER_GB_MONTH: "15000";
	ReviewSandbox: DurableObjectNamespace<import("./worker/index").ReviewSandbox>;
	QaSandbox: DurableObjectNamespace<import("./worker/index").QaSandbox>;
	REVIEW_WORKFLOW: Workflow<Parameters<import("./worker/index").HostedReviewWorkflow['run']>[0]['payload']>;
	QA_WORKFLOW: Workflow<Parameters<import("./worker/index").HostedQaWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "ReviewSandbox" | "QaSandbox";
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_URL" | "LEGACY_APP_URL" | "GLAMA_MAINTAINER_EMAIL" | "GITHUB_APP_SLUG" | "CORPUS_CONSENT_VERSION" | "DEV_BYPASS_AUTH" | "STRIPE_METER_EVENT_NAME" | "STRIPE_PRICE_ID" | "CONTAINER_CPU_MICRO_USD_PER_VCPU_SECOND" | "CONTAINER_MEMORY_MICRO_USD_PER_GIB_SECOND" | "CONTAINER_DISK_MICRO_USD_PER_GB_SECOND" | "R2_STORAGE_MICRO_USD_PER_GB_MONTH">> {}
}
declare module "*.mjs" {
	const value: string;
	export default value;
}