import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

import { builtinModelCatalog } from '../src/config.js';
import { loadPricing } from '../src/cost/compute.js';
import { HARNESSES } from '../src/harness/registry.js';

describe('generated compatibility catalog', () => {
  it('contains only reachable, priced models backed by registered harnesses', () => {
    const catalog = builtinModelCatalog();
    const pricing = loadPricing();
    const ids = catalog.map(({ model }) => model.id);

    expect(new Set(ids).size).toBe(ids.length);
    expect(catalog.length).toBeGreaterThan(0);
    for (const { model, presets } of catalog) {
      expect(presets, `${model.id} must be reachable from a preset`).not.toHaveLength(0);
      expect(HARNESSES[model.harness], `${model.id} harness`).toBeDefined();
      expect(pricing[model.pricing_key ?? model.id], `${model.id} pricing`).toBeDefined();
    }
  });

  it('publishes every tested model, preset, auth name, and harness in the generated matrix', () => {
    const matrix = readFileSync(join(process.cwd(), 'docs', 'compatibility.md'), 'utf8');
    expect(matrix).toContain('Generated by scripts/render-compatibility.mjs');
    for (const { model, presets } of builtinModelCatalog()) {
      expect(matrix).toContain(`\`${model.id}\``);
      expect(matrix).toContain(`\`${model.secret}\``);
      for (const preset of presets) expect(matrix).toContain(`\`${preset}\``);
    }
    for (const harnessId of Object.keys(HARNESSES)) {
      expect(matrix).toContain(`\`${harnessId}\``);
    }
  });
});
